services:
  - type: web
    name: electricStore
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod